/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author ricardoxd
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestanas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botonGenerar = new javax.swing.JButton();
        restricciones = new javax.swing.JTextField();
        variables = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pestanaTabla2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_simplex = new javax.swing.JTable();
        boton_solucion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_resultado = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_operaciones = new javax.swing.JTable();
        boton_iteraccion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_salir = new javax.swing.JMenuItem();
        Opciones = new javax.swing.JMenu();
        Menu_opciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        pestanas.setBackground(new java.awt.Color(255, 255, 255));
        pestanas.setForeground(new java.awt.Color(31, 31, 31));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        botonGenerar.setText("Generar Tabla");
        jPanel1.add(botonGenerar);
        botonGenerar.setBounds(310, 150, 210, 29);
        jPanel1.add(restricciones);
        restricciones.setBounds(170, 140, 118, 27);
        jPanel1.add(variables);
        variables.setBounds(170, 170, 118, 27);

        jLabel1.setText("Restricciones");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(43, 144, 120, 17);

        jLabel2.setText("Variables");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(43, 177, 110, 17);

        pestanas.addTab("Datos", jPanel1);

        pestanaTabla2.setBackground(new java.awt.Color(255, 255, 255));
        pestanaTabla2.setLayout(null);

        tabla_simplex.setBackground(new java.awt.Color(254, 254, 254));
        tabla_simplex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"S1", "2", "1", "1", "0", "0", "18"},
                {"S2", "2", "3", "0", "1", "0", "42"},
                {"S3", "3", "1", "0", "0", "1", "24"},
                {"Z", "-3", "-2", "0", "0", "0", "0"}
            },
            new String [] {
                "A", "X1", "X2", "S1", "S2", "S3", "Solución"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_simplex.setGridColor(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(tabla_simplex);

        pestanaTabla2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 690, 350);

        boton_solucion.setText("Solución");
        pestanaTabla2.add(boton_solucion);
        boton_solucion.setBounds(310, 30, 130, 29);

        pestanas.addTab("Tabla", pestanaTabla2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        tabla_resultado.setBackground(new java.awt.Color(254, 254, 254));
        tabla_resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "                 S1", "                 S2", "                 S3", "                 S4"
            }
        ));
        tabla_resultado.setGridColor(new java.awt.Color(0, 0, 153));
        jScrollPane2.setViewportView(tabla_resultado);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 122, 460, 320);

        tabla_operaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Operaciones"
            }
        ));
        jScrollPane3.setViewportView(tabla_operaciones);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(480, 120, 240, 320);

        boton_iteraccion.setText("Interacción");
        jPanel3.add(boton_iteraccion);
        boton_iteraccion.setBounds(270, 60, 160, 29);

        pestanas.addTab("Resultados", jPanel3);

        getContentPane().add(pestanas);
        pestanas.setBounds(20, 20, 740, 500);

        jMenu1.setText("Archivo");

        Menu_salir.setText("Salir");
        jMenu1.add(Menu_salir);

        jMenuBar1.add(jMenu1);

        Opciones.setText("Opciones");

        Menu_opciones.setText("Configuracion");
        Opciones.add(Menu_opciones);

        jMenuBar1.add(Opciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotonGenerar() {
        return botonGenerar;
    }

    public void setBotonGenerar(JButton botonGenerar) {
        this.botonGenerar = botonGenerar;
    }

    public JButton getBoton_iteraccion() {
        return boton_iteraccion;
    }

    public void setBoton_iteraccion(JButton boton_iteraccion) {
        this.boton_iteraccion = boton_iteraccion;
    }

    public JButton getBoton_solucion() {
        return boton_solucion;
    }

    public void setBoton_solucion(JButton boton_solucion) {
        this.boton_solucion = boton_solucion;
    }

    public JMenuItem getMenu_opciones() {
        return Menu_opciones;
    }

    public void setMenu_opciones(JMenuItem Menu_opciones) {
        this.Menu_opciones = Menu_opciones;
    }

    public JMenuItem getMenu_salir() {
        return Menu_salir;
    }

    public void setMenu_salir(JMenuItem Menu_salir) {
        this.Menu_salir = Menu_salir;
    }

   

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JPanel getPestanaTabla2() {
        return pestanaTabla2;
    }

    public void setPestanaTabla2(JPanel pestanaTabla2) {
        this.pestanaTabla2 = pestanaTabla2;
    }

    public JTabbedPane getPestanas() {
        return pestanas;
    }

    public void setPestanas(JTabbedPane pestanas) {
        this.pestanas = pestanas;
    }

    public JTextField getRestricciones() {
        return restricciones;
    }

    public void setRestricciones(JTextField restricciones) {
        this.restricciones = restricciones;
    }

    public JTable getTabla_operaciones() {
        return tabla_operaciones;
    }

    public void setTabla_operaciones(JTable tabla_operaciones) {
        this.tabla_operaciones = tabla_operaciones;
    }

    public JTable getTabla_resultado() {
        return tabla_resultado;
    }

    public void setTabla_resultado(JTable tabla_resultado) {
        this.tabla_resultado = tabla_resultado;
    }

    public JTable getTabla_simplex() {
        return tabla_simplex;
    }

    public void setTabla_simplex(JTable tabla_simplex) {
        this.tabla_simplex = tabla_simplex;
    }

    public JTextField getVariables() {
        return variables;
    }

    public void setVariables(JTextField variables) {
        this.variables = variables;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_opciones;
    private javax.swing.JMenuItem Menu_salir;
    private javax.swing.JMenu Opciones;
    private javax.swing.JButton botonGenerar;
    private javax.swing.JButton boton_iteraccion;
    private javax.swing.JButton boton_solucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pestanaTabla2;
    private javax.swing.JTabbedPane pestanas;
    private javax.swing.JTextField restricciones;
    private javax.swing.JTable tabla_operaciones;
    private javax.swing.JTable tabla_resultado;
    private javax.swing.JTable tabla_simplex;
    private javax.swing.JTextField variables;
    // End of variables declaration//GEN-END:variables




}
